### PR TITLE
simple graphite tags support

### LINKED ISSUE #36: Support Graphite 1.1 tagged metrics
https://grafana.com/blog/2018/01/11/graphite-1.1-teaching-an-old-dog-new-tricks/

The exporter should understand these and turn them into Prometheus labels. Beware however of inconsistent label sets – the client library will reject metrics (or fail collection completely) if multiple metrics with the same name have different sets of labels.

### PR DESCRIPTION
**Pull request by glightfoot**
Simple implementation of graphite tag support without breaking out into packages.

Fixes #36 

Benchmark on master:
```
$ go test -bench=. 
goos: darwin
goarch: amd64
pkg: github.com/prometheus/graphite_exporter
BenchmarkProcessLine1-12           17187             69149 ns/op
BenchmarkProcessLine5-12            3506            343312 ns/op
BenchmarkProcessLine50-12            348           3451278 ns/op
PASS
ok      github.com/prometheus/graphite_exporter 4.920s
```

Benchmark with tag parsing:
```
$ go test -bench=. 
goos: darwin
goarch: amd64
pkg: github.com/prometheus/graphite_exporter
BenchmarkProcessLine1-12           15975             75466 ns/op
BenchmarkProcessLine5-12            3189            374342 ns/op
BenchmarkProcessLine50-12            318           3767328 ns/op
PASS
ok      github.com/prometheus/graphite_exporter 5.010s
```

The benchmark only replaces four metrics with tagged equivalents, so I am not sure how exact the parsing hit is... It may also be greater when there is a large number of metrics in the `metricNameAndKeys` cache. The cache was added to address the concerns about inconsistent label keys referenced in the original issue, but there may be a better way to do that.

@matthiasr

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -126,6 +173,37 @@ func (c *graphiteCollector) processLines() {
 	}
 }
 
+func parseMetricNameAndTags(name string, labels prometheus.Labels) (string, error) {
+	if strings.ContainsRune(name, ';') {
```
Comment (matthiasr) [inline main.go:177]: I think this could be simpler (and save us from traversing the string twice) if we [unconditionally split the string](https://play.golang.org/p/lUaD6ynuMTm) and iterate over the (potentially zero) tag parts.

Why does this function take labels as an argument? Could it return a fresh `prometheus.Labels` instead?

File: main.go [hunk 2]
```diff
@@ -136,16 +214,42 @@ func (c *graphiteCollector) processLine(line string) {
 	}
 	originalName := parts[0]
 	var name string
-	mapping, labels, present := c.mapper.GetMapping(originalName, mapper.MetricTypeGauge)
+	var err error
+	mapping, labels, mappingPresent := c.mapper.GetMapping(originalName, mapper.MetricTypeGauge)
```
Comment (matthiasr) [inline main.go:218]: The mapping applies to the metric name, so I think we need to extract the Graphite tags before attempting GetMapping.

File: .golangci.yml [hunk 3]
```diff
@@ -1,8 +1,11 @@
 run:
   modules-download-mode: vendor
-
+  skip-dirs:
+    - vendor
+    - e2e
 # Run only staticcheck for now. Additional linters will be enabled one-by-one.
```
Comment (matthiasr) [inline .golangci.yml:6]: This comment is now outdated

File: main.go (hunk 1 above)
Comment (glightfoot) [reply main.go]: of course. I had it taking labels as an arg since maps are sort of a reference type in go, but making a new set each time and returning it is much cleaning

File: main.go (hunk 2 above)
Comment (glightfoot) [reply main.go]: Done

File: main.go [hunk 4]
```diff
@@ -126,26 +173,71 @@ func (c *graphiteCollector) processLines() {
...
 
-	if (present && mapping.Action == mapper.ActionTypeDrop) || (!present && c.strictMatch) {
+	parsedName, labels, err := parseMetricNameAndTags(originalName)
+	if err != nil {
+		level.Info(c.logger).Log("msg", "Invalid tags", "line", line, "err", err.Error())
+	}
+
+	mapping, mappingLabels, mappingPresent := c.mapper.GetMapping(parsedName, mapper.MetricTypeGauge)
+
+	// add mapping labels to parsed labels
```
Comment (glightfoot) [inline main.go:221]: Should mapping labels override parsed labels?

**Comment by glightfoot** [comment]
I wanted to double check some things. I guess the only concern I have left is the addition of the metric name and label key cache. It prevents mismatched metrics from coming in, so it does what it's supposed to, but is that the behavior it should have?

File: main.go (hunk 4 above)
Comment (matthiasr) [reply main.go:221]: That seems right to me.

**Comment by matthiasr** [comment]
If we can, we should export them anyway – the statsd exporter does that by implementing its own unchecked collector. For a start, I think it is okay if we are restrictive now and relax it later (the other way around not so much).

**Comment by matthiasr** [comment]
Unless you want to switch to that collector right away …

**Comment by glightfoot** [comment]
I'm not too familiar with the collector, but taking a look at the statsd exporter, it looks like the only change should be to change the describe method to not return anything?  e.g.

```
func (c graphiteCollector) Describe(ch chan<- *prometheus.Desc) {
}
```

**Comment by matthiasr** [comment]
That turns off the validations in the Prometheus client. I think it's the
core of allowing "conflicting" label sets but I don't know what else there
is. Let's try?

**Comment by glightfoot** [comment]
Seems to work. Added a test and an e2e test and it appears to accept inconsistent label sets fine with the unchecked collector

**Comment by glightfoot** [comment]
I don't have a graphite setup to test this, but it appears to be working with my bash testing and go tests. I'd love it if someone could test this in a real setup, but otherwise I think this is ready for review

**Comment by glightfoot** [comment]
Improved the benchmarks a little more.

```
go test -bench=. 
goos: darwin
goarch: amd64
pkg: github.com/prometheus/graphite_exporter
BenchmarkProcessLineMixed1-12              17810             66754 ns/op
BenchmarkProcessLineMixed5-12               3621            332130 ns/op
BenchmarkProcessLineMixed50-12               360           3320201 ns/op
BenchmarkProcessLineUntagged-12           378669              3223 ns/op            1204 B/op         21 allocs/op
BenchmarkProcessLineTagged-12             331599              3608 ns/op            1603 B/op         24 allocs/op
PASS
ok      github.com/prometheus/graphite_exporter 7.265s
```

File: main.go [hunk 5]
```diff
@@ -63,13 +63,23 @@ var (
...
+	tagParseFailures = prometheus.NewCounter(
+		prometheus.CounterOpts{
+			Name: "graphite_tag_parse_failures",
+			Help: "Total count of samples with invalid tags",
+		})
+	invalidMetrics = prometheus.NewCounter(
+		prometheus.CounterOpts{
+			Name: "graphite_invalid_metrics",
+			Help: "Total count of metrics dropped due to mismatched label keys",
+		})
```
Comment (matthiasr) [inline main.go:75]: This metric is now entirely unused again, since we made this not an error:

```suggestion
```

File: main.go [hunk 6]
```diff
@@ -257,6 +304,8 @@ func main() {
 	logger := promlog.New(promlogConfig)
 
 	prometheus.MustRegister(sampleExpiryMetric)
+	prometheus.MustRegister(tagParseFailures)
+	prometheus.MustRegister(invalidMetrics)
```
Comment (matthiasr) [inline main.go:308]:
```suggestion
```

File: main.go [hunk 7]
```diff
@@ -126,26 +136,65 @@ func (c *graphiteCollector) processLines() {
...
 	}
+
 	originalName := parts[0]
-	var name string
-	mapping, labels, present := c.mapper.GetMapping(originalName, mapper.MetricTypeGauge)
 
-	if (present && mapping.Action == mapper.ActionTypeDrop) || (!present && c.strictMatch) {
+	parsedName, labels, err := parseMetricNameAndTags(originalName)
+	if err != nil {
+		level.Info(c.logger).Log("msg", "Invalid tags", "line", line, "err", err.Error())
```
Comment (matthiasr) [inline main.go:179]: Info feels like the wrong level here. It should either be a Warning since it's a problem, or Debug since it's user-input-driven and may be very high volume. To keep in line with the statsd exporter and the mapper package, I think it is the latter:
```suggestion
		level.Debug(c.logger).Log("msg", "Invalid tags", "line", line, "err", err.Error())
```

**Comment by glightfoot** [comment]
Thanks for the review and all the help! Made those changes and added a block to the README.

**Comment by matthiasr** [comment]
Great work, thank you very much for your contributions!
